version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: airflow_postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.10.5
    container_name: airflow_webserver
    # restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow_db
      AIRFLOW__WEBSERVER__SECRET_KEY: teste1234
      DATA_PATH: /opt/airflow/data
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./entrypoint.sh:/entrypoint.sh
      - ./scripts/:/scripts
      - ./db:/opt/airflow/db
    ports:
      - "8080:8080"
    entrypoint: ["/bin/bash", "/scripts/entrypoint.sh"]

  airflow-scheduler:
    image: apache/airflow:2.10.5
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow_db
      AIRFLOW__WEBSERVER__SECRET_KEY: teste1234
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./db:/opt/airflow/db
      - ./scripts/:/scripts
      - postgres_data:/var/lib/postgresql/data
    command: >
      bash -c "pip install -r /scripts/requirements.txt && airflow scheduler"

volumes:
  postgres_data: